<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>KFramework.MonoGameExtend</RootNamespace>
    <AssemblyName>KFramework.MonoGameExtend</AssemblyName>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\KFramework.MonoGame\KFramework.MonoGame.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="KTexturePacker.Parser">
      <HintPath>..\Need_DLL\KTexturePacker.Parser.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
