//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Images {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Images() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Resources.Images", typeof(Images).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap Blue_Progress {
            get {
                object obj = ResourceManager.GetObject("Blue_Progress", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap CheckF_Base2 {
            get {
                object obj = ResourceManager.GetObject("CheckF_Base2", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap CheckF_Hover {
            get {
                object obj = ResourceManager.GetObject("CheckF_Hover", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap CheckF_Pressed {
            get {
                object obj = ResourceManager.GetObject("CheckF_Pressed", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap Config_Base {
            get {
                object obj = ResourceManager.GetObject("Config_Base", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap Config_Base1 {
            get {
                object obj = ResourceManager.GetObject("Config_Base1", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap Config_Check_Off1 {
            get {
                object obj = ResourceManager.GetObject("Config_Check_Off1", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap Config_Check_On {
            get {
                object obj = ResourceManager.GetObject("Config_Check_On", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap Config_Hover {
            get {
                object obj = ResourceManager.GetObject("Config_Hover", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap Config_Pressed {
            get {
                object obj = ResourceManager.GetObject("Config_Pressed", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap Config_Radio_On {
            get {
                object obj = ResourceManager.GetObject("Config_Radio_On", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap Cross_Base {
            get {
                object obj = ResourceManager.GetObject("Cross_Base", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap Cross_Hover {
            get {
                object obj = ResourceManager.GetObject("Cross_Hover", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap Cross_Pressed {
            get {
                object obj = ResourceManager.GetObject("Cross_Pressed", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap Green_Progress {
            get {
                object obj = ResourceManager.GetObject("Green_Progress", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap Launch_Base {
            get {
                object obj = ResourceManager.GetObject("Launch_Base", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap Launch_Base1 {
            get {
                object obj = ResourceManager.GetObject("Launch_Base1", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap Launch_Hover {
            get {
                object obj = ResourceManager.GetObject("Launch_Hover", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap Launch_Pressed {
            get {
                object obj = ResourceManager.GetObject("Launch_Pressed", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap NEW_Progress_End__Blue_ {
            get {
                object obj = ResourceManager.GetObject("NEW_Progress_End__Blue_", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap NEW_Progress_End__Green_ {
            get {
                object obj = ResourceManager.GetObject("NEW_Progress_End__Green_", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap pfffft {
            get {
                object obj = ResourceManager.GetObject("pfffft", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap Radio_Unactive {
            get {
                object obj = ResourceManager.GetObject("Radio_Unactive", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap server_base {
            get {
                object obj = ResourceManager.GetObject("server_base", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap textboxes {
            get {
                object obj = ResourceManager.GetObject("textboxes", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
    }
}
